//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC_ProgIII
{


    public partial class TrabajaConNosotros
    {
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtDni;
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.DropDownList ddlPuesto;
        protected global::System.Web.UI.WebControls.FileUpload fileCV;
        protected global::System.Web.UI.WebControls.Button btnEnviar;
    }
}

