//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend
{


    public partial class Debug
    {

        /// <summary>
        /// Control pnlUsuarioLogueado.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlUsuarioLogueado;

        /// <summary>
        /// Control lblNombre.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNombre;

        /// <summary>
        /// Control lblApellido.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblApellido;

        /// <summary>
        /// Control lblEmail.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmail;

        /// <summary>
        /// Control lblIdUsuario.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblIdUsuario;

        /// <summary>
        /// Control lblIdRol.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblIdRol;

        /// <summary>
        /// Control lblNombreRol.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNombreRol;

        /// <summary>
        /// Control pnlEsAdmin.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEsAdmin;

        /// <summary>
        /// Control pnlNoAdmin.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoAdmin;

        /// <summary>
        /// Control pnlNoLogueado.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoLogueado;

        /// <summary>
        /// Control btnRefresh.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnRefresh;
    }
}

